### ISSUE TITLE
Compiling Resources as the static resources 

### ISSUE THREAD

**Issue by Vladimirchizh** [Lambozhuang/stable-diffusion-demo#1]
Could you clarify what do you mean by that line? 
Ideally could you guide us through?

**Comment by Lambozhuang** [comment]
I updated the README.md 
see https://github.com/Lambozhuang/StableDiffusionDemo/commit/8b0e1ef73a01a59eca36b0dde6b35cfe5f6bab6d

Hope this will explain better :)

**Comment by Vladimirchizh** [comment]
thank you so much!
